<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Wealth Management - Email</title>
    <style type="text/css"></style>
  </head>

  <body>
    <div style="font-family: Arial, sans-serif; font-size: 13.5px; text-align: justify; margin-bottom: 25px;">
      <p style="margin-bottom: 20px;font-weight: bold;">Dear Valued Customer,</p>
      <p>
        Please find attached your Unit Trust ${accountNo!} e-Statement dated ${date!} for your reference and further action.
      </p>
      <p style="line-height: 1.2">
        For security reasons, the attachment is password protected. To access,
        please use the default password, which consists of eight characters in
        the format given below:
      </p>
      <p style="line-height: 1.2">
        <span style="font-weight: bold;"
          ><span style="margin-right: 10px;">•&#160;</span
          ><u>1<sup>st</sup> and 2<sup>nd</sup> characters</u>:</span
        ><br />
        <div style="margin-left: 20px"
          >Key in the first two characters of your name (in uppercase), as per
          your MyKad (for Malaysian individuals), passport (for foreigners) or
          your registered company name as per registered with the Registrar of
          Companies (for companies).</div
        >
      </p>
      <p style="line-height: 1.2">
        <span style="font-weight: bold"
          ><span style="margin-right: 10px;">•&#160;</span
          ><u>3<sup>rd</sup> to 8<sup>th</sup> characters</u>:</span
        ><br />
        <div style="margin-left: 20px"
          >Key in the last six digits of your MyKad number (for Malaysian
          individuals)<sup>1</sup>, passport number (for foreigners)<sup>2</sup>
          or company registration number as per the Bank’s record (for
          companies)<sup>3</sup>.
        </div>
      </p>

      <p style="margin-left: 20px; margin-top: 20px; line-height: 1.2; font-style: italic;">
        Note: If your Identification Document number (MyKad/Passport/Company
        registration number) length is less than 6 digits, please use an
        asterisk (*) to fill in the remaining digit(s) to make it six characters
        long <sup>4</sup>.
      </p>
      <p>
        Should you require any assistance, please call our Contact Centre at 03 26 900 900 or email us at <u>contactcenter@bankislam.com.my.</u> Let’s GO GREEN.
      </p>
      <p style="line-height: 1.2; margin-top: 30px">
        Regards,<br /><span style="font-weight: bold"
          >BANK ISLAM MALAYSIA BERHAD</span
        >
      </p>

      <p style="font-style: italic; font-size: 13.5px;">
        This is a computer-generated email. No signature is required and replies
        to this email will not be monitored.
      </p>

      <p style="margin-bottom: 30px; margin-top: 25px;">_____________________________</p>

      <div style="font-size: 11px;">
      <table style="font-family: Arial, sans-serif; width: 100%; border-collapse: collapse; font-size: 11px;">
          <tr>
            <td style="width: 20px; vertical-align: text-top;"><sup>1</sup></td>
            <td>
              If your name is <strong>AXMAD FAZLF BIN MOHD</strong> and MyKad
              number is <strong>290111-63-0497</strong>, your default password
              is <strong>AX630497</strong>.
            </td>
          </tr>
          <tr>
            <td style="width: 20px; vertical-align: text-top;"><sup>2</sup></td>
            <td>
              If your name is <strong>MZCHAEL JOHN</strong> and passport number
              is <strong>XJ31305752</strong>, your default password is
              <strong>MZ305752</strong>.
            </td>
          </tr>
          <tr>
            <td style="width: 20px; vertical-align: text-top;"><sup>3</sup></td>
            <td>
              If your registered company name is:
            </td>
          </tr>
          <tr>
            <td style="width: 20px; vertical-align: text-top;"></td>
            <td>
              a)&#160;<strong>QWFASHION SDN BHD</strong> and company number
              registered with the Bank is <strong>1187123-X</strong>, your
              default password is <strong>QW87123X</strong><br />
              b)&#160;<strong>LZDAZLY SDN BHD</strong> and company number registered
              with the Bank is <strong>124593845872</strong> (new format), your
              default password is <strong>LZ845872</strong>.
            </td>
          </tr>
          <tr>
            <td style="width: 20px; vertical-align: text-top;"><sup>4</sup></td>
            <td>
              If your registered company name is
              <strong>GMILLENIUM SDN BHD</strong> and company number registered
              with the Bank is <strong>4574</strong>, your default password is
              <strong>GM4574**</strong>
            </td>
          </tr>
        </table>
       
      <p style="font-size: 11px;line-height: 1.2;text-align: justify;font-style: italic; margin-top:10px;">
        Disclaimer: This email and any files transmitted with it is legally privileged, 
        restricted and intended solely for the use of the individual or entity to whom 
        it is addressed. If you are not the intended recipient, you are hereby notified 
        that you have received this email and any files transmitted with it in error and 
        that any use, dissemination, forwarding, printing or copying of this email and 
        any files transmitted with it is strictly prohibited. If you have received this 
        email and any files transmitted with it in error, please notify the sender 
        immediately and delete the email. </p>
      </div>
    </div>

    <hr/>
    <div style="margin-top: 40px;font-style: italic; font-family: Arial, sans-serif; font-size: 13.5px; text-align: justify">
      <p style="margin-bottom: 20px; font-weight: bold">Pelanggan yang dihormati,</p>
      <p>
        Sila dapatkan e-Penyata Unit Amanah ${accountNo!} bagi bulan ${date!} yang dilampirkan untuk rujukan anda dan tindakan selanjutnya.
      </p>
      <p style="line-height: 1.2">
        Bagi tujuan keselamatan, lampiran tersebut telah dilindungi dengan kata
        laluan. Untuk membuka lampiran tersebut, sila masukkan kata laluan unik
        yang terdiri daripada 8 aksara mengikut format di bawah:
      </p>
      <p>
        <span style="font-weight: bold"
          ><span style="margin-right: 10px;">•&#160; </span
          ><u>Aksara 1 dan 2</u>:</span
        ><br />
        <div style="margin-left: 20px">
          Taipkan dua aksara pertama nama anda (dalam huruf besar), seperti yang
          tertera dalam MyKad anda (untuk Individu Malaysia), Pasport (untuk
          Individu Warga Asing) atau nama syarikat berdaftar anda dengan
          Suruhanjaya Syarikat Malaysia (SSM) (untuk Syarikat).</div
        >
      </p>
      <p>
        <span style="font-weight: bold"
          ><span style="margin-right: 10px;">•&#160; </span
          ><u>Aksara 3 hingga 8</u>:</span
        ><br />
        <div style="margin-left: 20px">
          Taipkan 6 digit terakhir nombor MyKad anda (untuk Individu
          Malaysia)<sup>1</sup>, Pasport (untuk Individu Warga Asing)<sup
            >2</sup
          >
          atau Nombor Pendaftaran Syarikat (untuk Syarikat) yang didaftarkan
          dengan Bank<sup>3</sup>.
        </div>
      </p>

      <p style="margin-left: 20px; margin-top: 20px; line-height: 1.2">
        Nota: Jika nombor Dokumen Pengenalan Diri (MyKad/Pasport/Nombor
        Pendaftaran Syarikat) anda kurang daripada 6 digit, anda dikehendaki
        memasukkan tanda ‘*’ (asterisk) sebagai digit terakhir untuk membentuk
        jumlah aksara 6 digit<sup>4</sup>.
      </p>
      <p>
        Sekiranya anda memerlukan sebarang bantuan, sila hubungi Pusat Panggilan &amp; Khidmat 
        Pelanggan melalui 03-26 900 900 atau e-mel <u>contactcenter@bankislam.com.my.</u> Jom KE 
        ARAH BUMI HIJAU.
      </p>
      <p style="line-height: 1.2; margin-top: 30px">
        Terima kasih, <br />
        <span style="font-weight: bold">BANK ISLAM MALAYSIA BERHAD</span>
      </p>

      <p style=" font-size: 13.5px">
        Ini adalah e-mel yang dijana oleh komputer. Tiada tandatangan diperlukan
        dan balasan kepada e-mel ini tidak akan dipantau.
      </p>
     
       <p style="margin-bottom: 30px; margin-top: 25px;">_____________________________</p>

      <div style="font-size: 11px">
       <table style="font-family: Arial, sans-serif; width: 100%; border-collapse: collapse; font-size: 11px">
          <tr>
            <td style="width: 20px; vertical-align: text-top;"><sup>1</sup></td>
            <td>
              <i>Jika nama anda <strong>AXMAD FAZLF BIN MOHD</strong> dan Nombor
              MyKad ialah <strong>290111-63-0497</strong>, kata laluan anda
              ialah <strong>AX630497</strong></i>
            </td>
          </tr>
          <tr>
            <td style="width: 20px; vertical-align: text-top;"><sup>2</sup></td>
            <td>
              <i>Jika nama anda <strong>MZCHAEL JOHN</strong> dan nombor Pasport
              <strong>XJ31305752</strong>, kata laluan anda ialah
              <strong>MZ305752</strong>.</i>
            </td>
          </tr>
          <tr>
            <td style="width: 20px; vertical-align: text-top;"><sup>3</sup></td>
            <td>
              <i>Sekiranya nama syarikat berdaftar anda adalah:</i>
            </td>
          </tr>
          <tr>
            <td style="width: 20px; vertical-align: text-top;"></td>
            <td>
              <i>
              a)&#160;<strong>QWFASHION SDN. BHD</strong> dan nombor syarikat yang
              berdaftar dengan Bank ialah <strong>1187123-X</strong>, kata
              laluan anda ialah <strong>QW87123X</strong><br/>
              b)&#160;<strong>LZDAZLY SDN BHD</strong> dan nombor syarikat yang
              berdaftar dengan Bank ialah <strong>124593845872</strong> (format
              baru), laluan anda ialah <strong>LZ845872</strong>
              </i>
            </td>
          </tr>
          <tr>
            <td style="width: 20px; vertical-align: text-top;"><sup>4</sup></td>
            <td>
              <i>Jika nama syarikat berdaftar anda ialah
              <strong>GMILLENIUM SDN. BHD</strong> dan nombor syarikat yang
              berdaftar dengan Bank ialah <strong>4574</strong>, kata laluan
              anda ialah <strong>GM4574**</strong></i>
            </td>
          </tr>
        </table>
	      
	      <p style="line-height: 1.2;text-align: justify;margin-top:10px;">
          PENAFIAN: E-mel ini dan sebarang fail yang dihantar bersamanya mempunyai 
          keistimewaan di sisi undang-undang, terhad dan bertujuan semata-mata untuk 
          kegunaan individu atau entiti yang ditujukan. Sekiranya anda bukan penerima 
          yang dimaksudkan, anda dengan ini dimaklumkan bahawa anda telah menerima e-mel 
          ini dan sebarang fail yang dihantar dengannya secara silap dan sebarang 
          penggunaan, penyebaran, penghantaran, pencetakan atau penyalinan e-mel ini 
          dan sebarang fail yang dihantar bersamanya adalah dilarang sama sekali. 
          Jika anda telah menerima e-mel ini dan sebarang fail yang dihantar dengannya 
          secara silap, sila maklumkan kepada penghantar dengan segera dan padam e-mel 
          tersebut.
	      </p>
      </div>

    </div>
  </body>
</html>
