<!DOCTYPE html>
<html lang="en">
<head>
    <title>Notice Before Due 12 Months</title>
    <meta charset="utf-8" />
    <style type="text/css">
        @page {
            size: A4;
            margin-left: 50px;
            margin-right: 50px;
            margin-top: 30mm;
            margin-bottom: 24mm;
        }

        body {
            font-family: EmbArial;
            font-size: 8pt;
            text-align: justify;
            line-height: 1.2;
        }

        .break {
            word-wrap: break-word;
            white-space: normal;
            overflow-wrap: break-word;
        }

        .page-break {
            page-break-before: always;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .firstTable {
            margin-top: 10px;
        }

        .firstTable td {
            width: 50%;
            vertical-align: top;
        }

        .infoTable td {
            vertical-align: top;
        }

        .infoTableWidth {
            width: 11%;
        }

        .paymentInfoTable {
            width: 80%;
            margin-left: 40px;
        }

        .paymentInfoTable td {
            vertical-align: top;
            padding: 4px;
        }

        .paymentTableFirstTdWidth {
            width: 40%;
        }

        .paymentTableSecondTdWidth {
            width: 3%;
        }

        .topPadding {
            padding-top: 10px;
        }

        .alignText {
            text-align: center;
        }
    </style>
</head>
<body style="margin-top: 70px;">
    <main>
        <table>
            <tr>
                <td style="width: 10%;">REPORT ID</td>
                <td>: </td>
                <td class="break">LNA202P000001202908000043301917/12/20200001NUR RAUDHAH AMINAH BINTI ABBAS</td>
            </tr>
        </table>
        <table class="firstTable">
            <tr>
                <td>
                    <span>NUR RAUDHAH AMINAH BINTI ABBAS</span><br />
                    <span>KONDOMINIUM SERI IMPIANA</span><br />
                    <span>JALAN TASIK SELATAN 9</span><br />
                    <span>56100 CHERAS</span>
                </td>
                <td class="alignText"><span>Tarikh :</span><span>17/12/2020</span></td>
            </tr>
        </table>
        <p style="margin-top: 50px;">Assalamualaikum dan Salam Sejahtera,</p>
        <p>Tuan/puan,</p>

        <table class="infoTable">
            <tr>
                <td colspan="3">NOTIS&#160; PEMBERITAHUAN&#160; PEMBAYARAN&#160; KEUNTUNGAN&#160; BAGI&#160; AKAUN&#160; PEMBIAYAAN&#160; AR-RAHNU&#160; TAWARRUQ&#160;</td>
            </tr>
            <tr>
                <td class="infoTableWidth">NO. AKAUN</td>
                <td>:</td>
                <td class="break">12029080000433 ("AKAUN TERSEBUT")</td>
            </tr>
            <tr>
                <td class="infoTableWidth">CAWANGAN</td>
                <td>:</td>
                <td class="break">BANDAR BARU BANGI, SELANGOR</td>
            </tr>
        </table>
        <div>
            ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        </div>
        <p>Adalah dimaklumkan bahawa tempoh bayaran Jumlah Keuntungan dua belas (12) bulan akaun pembiayaan tuan/puan
            seperti dalam Perjanjian Pembiayaan Ar-Rahnu Tawarruq ("Jumlah Keuntungan") akan tamat empat belas (14) hari
            dari tarikh notis ini.</p>
        <p>Tuan/puan dikehendaki menjelaskan Jumlah Keuntungan Yang Perlu Dibayar sebelum/pada Tarikh
            Bayaran seperti yang dinyatakan di bawah.</p>
        <table class="paymentInfoTable">
            <tr>
                <td class="paymentTableFirstTdWidth">Jumlah Keuntungan</td>
                <td class="paymentTableSecondTdWidth">:</td>
                <td class="break">RM 1,781.14</td>
            </tr>
            <tr>
                <td class="paymentTableFirstTdWidth">Tarikh Bayaran</td>
                <td class="paymentTableSecondTdWidth">:</td>
                <td class="break">1/01/2021</td>
            </tr>
            <tr>
                <td class="paymentTableFirstTdWidth">Jumlah Bayaran Pendahuluan Semasa</td>
                <td class="paymentTableSecondTdWidth">:</td>
                <td class="break">RM.00</td>
            </tr>
        </table>
        <p>Jumlah Keuntungan Yang Perlu Dibayar = Jumlah Keuntungan - Jumlah Bayaran Pendahuluan Semasa.</p>
        <p>Kegagalan berbuat demikian akan menyebabkan Aset Gadaian Akaun Tersebut dilelong seperti yang dinyatakan di
            dalam Terma dan Syarat Pembiayaan dalam Perjanjian Pembiayaan Ar-Rahnu Tawarruq ("PART").</p>
        <p>Sila bawa bersama dokumen PART semasa membuat pembayaran. Sila abaikan notis ini sekiranya tuan/puan telah
            berbuat demikian.</p>
        <p>Nota: Agensi Kaunseling Dan Pengurusan Kredit telah ditubuhkan oleh Bank Negara Malaysia untuk menyediakan
            perkhidmatan pengurusan kewangan, kaunseling kredit, pendidikan kewangan dan penstrukturan semula pembiayaan secara percuma kepada individu. Untuk membuat
            pertanyaan, sila hubungi talian infoline 03-26167766.</p>
        <p class="topPadding">Sekian. Harap maklum.</p>
        <p class="topPadding">Ini adalah dokumen cetakan komputer dan tiada tandatangan diperlukan.</p>
        <p>BIMB019171220LNA202P</p>
    </main>
</body>
</html>