<!DOCTYPE html>
<html lang="en">
<head>
    <title>Notice Overdue Balance After Auction</title>
    <meta charset="utf-8" />
    <style type="text/css">
        @page {
            size: A4;
            margin-left: 50px;
            margin-right: 50px;
            margin-top: 30mm;
            margin-bottom: 24mm;
        }

        body {
            font-family: EmbArial;
            font-size: 8pt;
            text-align: justify;
            line-height: 2.5;
        }

        .break {
            word-wrap: break-word;
            white-space: normal;
            overflow-wrap: break-word;
        }

        .page-break {
            page-break-before: always;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .firstTable td {
            width: 50%;
            vertical-align: top;
        }

        .infoTable td {
            vertical-align: top;
        }

        .infoTableWidth {
            width: 11%;
        }

        .paymentInfoTable {
            width: 100%;
        }
        
        .paymentInfoTable td {
            vertical-align: top;
        }

        .paymentTableFirstTdWidth {
            width: 18%;
            padding-left:37px;
        }

        .paymentTableSecondTdWidth {
            width: 2%;
        }

        .alignText {
            text-align: center;
        }
    </style>
</head>
<body style="margin-top: 70px;">
    <main>
        <table>
            <tr>
                <td style="width: 10%;">REPORT ID</td>
                <td>: </td>
                <td class="break"> LNA207P000001202908000052301903/10/20200001MUHAMMAD NUH BIN IDRIS</td>
            </tr>
        </table>
        <table class="firstTable">
            <tr>
                <td>
                    <span>MUHAMMAD NUH BIN IDRIS</span><br />
                    <span>PANGSAPURI TENAGA INDAH</span><br />
                    <span>JALAN TAMAN PERMATA</span><br />
                    <span>LESTARI PERMAI</span><br />
                    <span>56100 CHERAS</span>
                </td>
                <td class="alignText"><span>Tarikh :</span><span>3/10/2020</span></td>
            </tr>
        </table>
        <div>Assalamualaikum dan Salam Sejahtera,</div>
        <div>Tuan/puan,</div>
        <table class="infoTable">
            <tr>
                <td colspan="3">NOTIS TUNTUTAN BAKI TUNGGAKAN SELEPAS LELONGAN BAGI AKAUN PEMBIAYAAN AR-RAHNU TAWARRUQ</td>
            </tr>
            <tr>
                <td class="infoTableWidth">NO. AKAUN</td>
                <td>:</td>
                <td class="break">12029080000523 ("AKAUN TERSEBUT")</td>
            </tr>
            <tr>
                <td class="infoTableWidth">CAWANGAN</td>
                <td>:</td>
                <td class="break">BANDAR BARU BANGI, SELANGOR</td>
            </tr>
        </table>
        <div>
            ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        </div>
        <div>Adalah dimaklumkan bahawa akaun pembiayaan tuan/puan seperti di atas telah dilelong pada 3/10/2020. Hasil lelongan masih tidak dapat menjelaskan sepenuhnya keberhutangan Akaun Tersebut dengan baki tunggakan seperti di bawah.</div>
        
        <table class="paymentInfoTable">
            <tr>
                <td class="paymentTableFirstTdWidth">Baki Tunggakan</td>
                <td class="paymentTableSecondTdWidth">:</td>
                <td class="break">RM 87.09</td>
            </tr>
        </table>
        <div>Bagi menyelesai penuh pembiayaan Akaun Tersebut, tuan/ puan hendaklah membayar Baki Tunggakan di atas seperti yang dinyatakan di dalam Terma dan Syarat Pembiayaan dalam Perjanjian<br/> Pembiayaan Ar-Rahnu Tawarruq ("PART").</div>
        <div>Sila bawa bersama dokumen PART semasa membuat penyelesaian penuh. Sila abaikan notis ini sekiranya tuan/puan telah berbuat demikian.</div>
        <div>Nota: Agensi Kaunseling Dan Pengurusan Kredit telah ditubuhkan oleh Bank Negara Malaysia untuk
            menyediakan perkhidmatan pengurusan kewangan, kaunseling kredit, pendidikan kewangan dan penstrukturan semula pembiayaan secara percuma kepada individu. Untuk membuat pertanyaan,
            sila hubungi talian infoline 03-26167766.</div>
        <div>Sekian. Harap maklum.</div>
        <div>Ini adalah dokumen cetakan komputer dan tiada tandatangan diperlukan.</div>
        <div>BIMB019031020LNA207P</div>
    </main>
</body>
</html>