<!DOCTYPE html>
<html lang="en">
<head>
    <title>Notice Before Due 6 Months</title>
    <meta charset="utf-8" />
    <style type="text/css">
        @page {
            size: A4;
            margin-left: 50px;
            margin-right: 50px;
            margin-top: 30mm;
            margin-bottom: 24mm;
        }

        body {
            font-family: EmbArial;
            font-size: 8pt;
            text-align: justify;
            line-height: 1.2;
        }

        .break {
            word-wrap: break-word;
            white-space: normal;
            overflow-wrap: break-word;
        }

        .page-break {
            page-break-before: always;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .firstTable {
            margin-top: 10px;
        }

        .firstTable td {
            width: 50%;
            vertical-align: top;
        }

        .infoTable td {
            vertical-align: top;
        }

        .infoTableWidth {
            width: 11%;
        }

        .paymentInfoTable {
            width: 80%;
            margin-left: 40px;
        }

        .paymentInfoTable td {
            vertical-align: top;
            padding: 4px;
        }

        .paymentTableFirstTdWidth {
            width: 40%;
        }

        .paymentTableSecondTdWidth {
            width: 3%;
        }

        .topPadding {
            padding-top: 10px;
        }

        .alignText {
            text-align: center;
        }
    </style>
</head>
<body style="margin-top: 70px;">
    <main>
        <table>
            <tr>
                <td style="width: 10%;">REPORT ID</td>
                <td>: </td>
                <td class="break">LNA201P000000350308041736550317/08/20200001NUR HIYAH BINTI FIRMAN</td>
            </tr>
        </table>
        <table class="firstTable">
            <tr>
                <td>
                    <span>NUR HIYAH BINTI FIRMAN</span><br />
                    <span>LOT 56 PADANG TENGKU</span><br />
                    <span>JALAN BADRIAH</span><br />
                    <span>56100 CHERAS</span>
                </td>
                <td class="alignText"><span>Tarikh :</span><span>17/08/2020</span></td>
            </tr>
        </table>
        <p style="margin-top: 50px;">Assalamualaikum dan Salam Sejahtera,</p>
        <p>Tuan/puan,</p>

        <table class="infoTable">
            <tr>
                <td colspan="3">NOTIS PEMBERITAHUAN PEMBAYARAN KEUNTUNGAN BAGI AKAUN PEMBIAYAAN AR-RAHNU TAWARRUQ</td>
            </tr>
            <tr>
                <td class="infoTableWidth">NO. AKAUN</td>
                <td>:</td>
                <td class="break">3503080417365 ("AKAUN TERSEBUT")</td>
            </tr>
            <tr>
                <td class="infoTableWidth">CAWANGAN</td>
                <td>:</td>
                <td class="break">Ar-Rahnu Bank Islam Pasir Mas</td>
            </tr>
        </table>
        <div>
            ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        </div>
        <p>Adalah dimaklumkan bahawa tempoh bayaran Jumlah Keuntungan enam (6) bulan akaun pembiayaan tuan/puan
            seperti dalam Perjanjian Pembiayaan Ar-Rahnu Tawarruq ("Jumlah Keuntungan") akan tamat empat belas (14) hari
            dari tarikh notis ini.</p>
        <p>Tuan/puan dikehendaki menjelaskan Jumlah Keuntungan Yang Perlu Dibayar sebelum/pada Tarikh
            Bayaran seperti yang dinyatakan di bawah.</p>
        <table class="paymentInfoTable">
            <tr>
                <td class="paymentTableFirstTdWidth">Jumlah Keuntungan</td>
                <td class="paymentTableSecondTdWidth">:</td>
                <td class="break">RM 1,853.26</td>
            </tr>
            <tr>
                <td class="paymentTableFirstTdWidth">Tarikh Bayaran</td>
                <td class="paymentTableSecondTdWidth">:</td>
                <td class="break">1/09/2020</td>
            </tr>
            <tr>
                <td class="paymentTableFirstTdWidth">Jumlah Bayaran Pendahuluan Semasa</td>
                <td class="paymentTableSecondTdWidth">:</td>
                <td class="break">RM 1,700.00</td>
            </tr>
        </table>
        <p>Jumlah Keuntungan Yang Perlu Dibayar = Jumlah Keuntungan - Jumlah Bayaran Pendahuluan Semasa.</p>
        <p>Kegagalan berbuat demikian akan menyebabkan Aset Gadaian Akaun Tersebut dilelong seperti yang dinyatakan di
            dalam Terma dan Syarat Pembiayaan dalam Perjanjian Pembiayaan Ar-Rahnu Tawarruq ("PART").</p>
        <p>Sila bawa bersama dokumen PART semasa membuat pembayaran. Sila abaikan notis ini sekiranya tuan/puan telah
            berbuat demikian.</p>
        <p>Nota: Agensi Kaunseling Dan Pengurusan Kredit telah ditubuhkan oleh Bank Negara Malaysia untuk menyediakan
            perkhidmatan pengurusan kewangan, kaunseling kredit, pendidikan kewangan dan penstrukturan semula pembiayaan secara percuma kepada individu. Untuk membuat
            pertanyaan, sila hubungi talian infoline 03-26167766.</p>
        <p class="topPadding">Sekian. Harap maklum.</p>
        <p class="topPadding">Ini adalah dokumen cetakan komputer dan tiada tandatangan diperlukan.</p>
        <p>BIMB503170820LNA201P</p>
    </main>
</body>
</html>