<!DOCTYPE html>
<html lang="en">
<head>
    <title>Notice Auction Balance</title>
    <meta charset="utf-8" />
    <style type="text/css">
        @page {
            size: A4;
            margin-left: 50px;
            margin-right: 50px;
            margin-top: 30mm;
            margin-bottom: 24mm;
        }

        body {
            font-family: EmbArial;
            font-size: 8pt;
            text-align: justify;
            line-height: 1.2;
        }

        .break {
            word-wrap: break-word;
            white-space: normal;
            overflow-wrap: break-word;
        }

        .page-break {
            page-break-before: always;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .firstTable {
            margin-top: 10px;
        }

        .firstTable td {
            width: 50%;
            vertical-align: top;
        }

        .infoTable td {
            vertical-align: top;
        }

        .infoTableWidth {
            width: 11%;
        }

        .paymentInfoTable {
            width: 80%;
            margin-left: 40px;
        }

        .paymentInfoTable td {
            vertical-align: top;
            padding: 4px;
        }

        .paymentTableFirstTdWidth {
            width: 40%;
        }

        .paymentTableSecondTdWidth {
            width: 3%;
        }

        .topPadding {
            padding-top: 10px;
        }

        .alignText {
            text-align: center;
        }
    </style>
</head>
<body style="margin-top: 70px;">
    <main>
        <table>
            <tr>
                <td style="width: 10%;">REPORT ID</td>
                <td>: </td>
                <td class="break">LNA206P000001202908000054801903/09/20200001MUHAMMAD NUH BIN IDRIS BRN000 - Bank Wide OUTО</td>
            </tr>
        </table>
        <table class="firstTable">
            <tr>
                <td>
                    <span>MUHAMMAD NUH BIN IDRIS</span><br />
                    <span>PANGSAPURI TENAGA INDAH</span><br />
                    <span>JALAN TAMAN PERMATA</span><br />
                    <span>LESTARI PERMAI</span><br/>
                    <span>56100 CHERAS</span>
                </td>
                <td class="alignText"><span>Tarikh :</span><span>3/09/2020</span></td>
            </tr>
        </table>
        <p style="margin-top: 50px;">Assalamualaikum dan Salam Sejahtera,</p>
        <p>Tuan/puan,</p>

        <table class="infoTable">
            <tr>
                <td colspan="3">NOTIS LEBIHAN HASIL LELONGAN BAGI AKAUN PEMBIAYAAN AR-RAHNU TAWARRUQ</td>
            </tr>
            <tr>
                <td class="infoTableWidth">NO. AKAUN</td>
                <td>:</td>
                <td class="break">12029080000548 ("AKAUN TERSEBUT")</td>
            </tr>
            <tr>
                <td class="infoTableWidth">AMAUN</td>
                <td>:</td>
                <td class="break"> RM 568.01 ("WANG TERSEBUT")</td>
            </tr>
            <tr>
                <td class="infoTableWidth">CAWANGAN</td>
                <td>:</td>
                <td class="break"> BANDAR BARU BANGI, SELANGOR</td>
            </tr>
        </table>
        <div>
            ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        </div>
        <p>Adalah dimaklumkan bahawa akaun pembiayaan tuan/puan seperti di atas telah dilelong
            pada 4/08/2020. ("Tarikh Lelongan"). Tuan/puan diminta untuk datang ke cawangan Ar-Rahnu Bank
            Islam di alamat yang tertera di dalam PART untuk menuntut Wang Tersebut bagi Akaun Tersebut.</p>
        <p>Jika tuntutan tidak dibuat melebihi tempoh dua belas (12) bulan dari Tarikh lelongan, Wang
            Tersebut akan diserahkan kepada Pendaftar Wang Tidak Dituntut, selaras dengan Akta Wang Tak Dituntut 1965 (Pindaan 2002).</p>
        
        <p>Sila bawa bersama MyKad semasa membuat tuntutan Wang Tersebut.</p>
        
        <p>Nota: Agensi Kaunseling Dan Pengurusan Kredit telah ditubuhkan oleh Bank Negara Malaysia untuk menyediakan perkhidmatan pengurusan kewangan, kaunseling kredit, pendidikan kewangan dan penstrukturan semula pembiayaan secara percuma kepada individu. Untuk membuat pertanyaan,sila hubungi talian infoline 03-26167766.</p>
        <p class="topPadding">Sekian. Harap maklum.</p>
        <p class="topPadding">Ini adalah dokumen cetakan komputer dan tiada tandatangan diperlukan.</p>
        <p>BIMB019030920LNA206P</p>
    </main>
</body>
</html>