<!DOCTYPE html>
<html lang="en">
<head>
    <title>Notice On Overdue Payment 18 months</title>
    <meta charset="utf-8" />
    <style type="text/css">
        @page {
            size: A4;
            margin-left: 50px;
            margin-right: 50px;
            margin-top: 30mm;
            margin-bottom: 24mm;
        }

        body {
            font-family: EmbArial;
            font-size: 8pt;
            text-align: justify;
            line-height: 2.5;
        }

        .break {
            word-wrap: break-word;
            white-space: normal;
            overflow-wrap: break-word;
        }

        .page-break {
            page-break-before: always;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .firstTable td {
            width: 50%;
            vertical-align: top;
        }

        .infoTable td {
            vertical-align: top;
        }

        .infoTableWidth {
            width: 11%;
        }

        .paymentInfoTable {
            width: 100%;
        }

        .paymentInfoTable td {
            vertical-align: top;
        }

        .paymentTableFirstTdWidth {
            width: 23%;
        }

        .paymentTableSecondTdWidth {
            width: 1%;
        }

        .alignText {
            text-align: center;
        }
    </style>
</head>
<body style="margin-top: 70px;">
    <main>
        <table>
            <tr>
                <td style="width: 10%;">REPORT ID</td>
                <td>: </td>
                <td class="break">LNA204BP000000350308041708850301/07/20210001WAN MEHMED BIN WAN MALLIQ</td>
            </tr>
        </table>
        <table class="firstTable">
            <tr>
                <td>
                    <span>WAN MEHMED BIN WAN MALLIQ</span><br />
                    <span>APARTMENT JELATEK INDAH</span><br />
                    <span>JALAN TASIK SELATAN 2</span><br />
                    <span>56100 CHERAS</span><br />
                </td>
                <td class="alignText"><span>Tarikh :</span><span>1/07/2021</span></td>
            </tr>
        </table>
        <div>Assalamualaikum dan Salam Sejahtera,</div>
        <div>Tuan/puan,</div>
        <table class="infoTable">
            <tr>
                <td colspan="3">NOTIS TUNTUTAN TUNGGAKAN BAGI AKAUN PEMBIAYAAN AR-RAHNU TAWARRUQ</td>
            </tr>
            <tr>
                <td class="infoTableWidth">NO. AKAUN</td>
                <td>:</td>
                <td class="break"> 3503080417088 ("AKAUN TERSEBUT")</td>
            </tr>
            <tr>
                <td class="infoTableWidth">CAWANGAN</td>
                <td>:</td>
                <td class="break">Ar-Rahnu Bank Islam Pasir Mas</td>
            </tr>
        </table>
        <div>
            ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        </div>
        <div>Adalah dimaklumkan bahawa akaun pembiayaan tuan/puan seperti di atas telah tertunggak bermula dari tarikh notis ini.</div>
        <table class="paymentInfoTable">
            <tr>
                <td class="paymentTableFirstTdWidth">Jumlah Tunggakan Semasa</td>
                <td class="paymentTableSecondTdWidth">:</td>
                <td class="break">RM 321.64</td>
            </tr>
        </table>
        <div>Tuan/Puan dikehendaki menjelaskan jumlah tertunggak dalam tempoh empat belas (14) hari daripada tarikh notis ini bagi tujuan penyelesaian penuh Akaun Tersebut sebelum Aset Gadaian Akaun Tersebut dilelong seperti yang dinyatakan di dalam Terma dan Syarat Pembiayaan dalam Perjanjian Pembiayaan Ar-Rahnu Tawarruq ("PART").</div>
        <div>Untuk makluman, Jumlah Tunggakan Semasa di atas dikira sehingga tarikh notis ini sahaja.</div>
        <div>Jumlah sebenar yang perlu dijelaskan oleh tuan/puan akan dikira semula pada tarikh
            penyelesaian penuh dibuat.</div>
            <div>Sila bawa bersama dokumen PART semasa membuat penyelesaian penuh. Sila abaikan notis ini
                sekiranya tuan/puan telah berbuat demikian.</div>
        <div>Nota: Agensi Kaunseling Dan Pengurusan Kredit telah ditubuhkan oleh Bank Negara Malaysia
            untuk menyediakan perkhidmatan pengurusan kewangan, kaunseling kredit, pendidikan kewangan dan penstrukturan semula pembiayaan secara percuma kepada individu. Untuk membuat pertanyaan, sila hubungi talian infoline 03-26167766.</div>
        <div>Sekian. Harap maklum.</div>
        <div>Ini adalah dokumen cetakan komputer dan tiada tandatangan diperlukan.</div>
        <div>BIMB503020721LNA204BP</div>
    </main>
</body>
</html>